### ISSUE TITLE
support echo commnd

### ISSUE THREAD

**Issue by LuckyTom1024** [arana-db/kiwi-cpp#19]
### Which PikiwiDB functionalities are relevant/related to the feature request?

other

### Description

support echo, auth commnd

### Proposed solution

echo: refer to https://redis.io/docs/latest/commands/?name=echo

### Alternatives considered

nothing

**Comment by longfar-ncy** [comment]
@JW-Gao

**Comment by Antarctica000** [comment]
我可以做这个
