### ISSUE TITLE
add CmdRes error type

### ISSUE THREAD

**Issue by LuckyTom1024** [arana-db/kiwi-cpp#21]
### Is this a regression?

None

### Is this a regression?

Yes

### Description

不再使用 kErrOther 等错误，添加下 kErrMoved 等类型的错误

### Screenshots or videos

![image](https://github.com/user-attachments/assets/e010fba1-5f2e-45ab-aa16-932e627f290a)

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by LuckyTom1024** [comment]
@panlei-coder

**Comment by luky116** [comment]
同：https://github.com/arana-db/kiwi/issues/22
