### ISSUE TITLE
[Go test] go test 依赖的 go-redis 升级到最新版本 v9.6.1

### ISSUE THREAD

**Issue by gukj-spel** [arana-db/kiwi-cpp#35]
### Description

目前 kiwi gtest 使用的 go-redis 为 v9.0.4， 最新版的 v9.6.1 相较于 v9..0.4 有了一些升级
* v9.3.0 支持了 json 这个 redis data type 
* 支持了更多 redis 命令，例如 WAITAOF, CLIENT SETINFO, MONITOR 等
* 修改了一些 bug
可以考虑将 go-redis 进行升级

**Comment by luky116** [comment]
待添加测试

**Comment by luky116** [comment]
done
