### ISSUE TITLE
项目 license 注释的权限改为 arana 社区

### ISSUE THREAD

**Issue by luky116** [arana-db/kiwi-cpp#39]
### Is this a regression?

None

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by luky116** [comment]
@Iam-WenYi

**Comment by Iam-WenYi** [comment]
已经完成
