### ISSUE TITLE
Kiwi 编译流程中，多了一个 K

### ISSUE THREAD

**Issue by Iam-WenYi** [arana-db/kiwi-cpp#75]
### Is this a regression?

None

### Description

![image](https://github.com/user-attachments/assets/93a1ddb8-cf86-4c8d-a859-8c23c27d70a8)

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by lqxhub** [comment]
不是多了一个K,是 宏定义重复定义了, #85 这个pr修复了
