### ISSUE TITLE
支持 hello 命令

### ISSUE THREAD

**Issue by luky116** [arana-db/kiwi-cpp#82]
### Is this a regression?

None

fix #119 

### Screenshots or videos

![images](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by marsevilspirit** [comment]
asign me pls
